# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\py\qt_01\kursovoy\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import subprocess
from PyQt5 import QtCore, QtGui, QtWidgets
from psutil import process_iter


class Ui_ProcForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 558)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)        
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)        
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "OS Processes"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "PID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Minor PF"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Major PF"))                
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Process Name"))

class ProcWindow(Ui_ProcForm):
    def __init__(self, Form) -> None:
        super().__init__()
        self.setupUi(Form)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.horizontalHeader().setStretchLastSection(True )
        self.fill_in()

    def get_page_faults(self, pid=1):
        command = f"ps -o min_flt,maj_flt {pid}"
        getVersion =  subprocess.Popen(command, shell=True, stdout=subprocess.PIPE).stdout
        version =  getVersion.read()

        outp = version.decode(encoding="utf-8")
        outp = outp.split(' ')
        result = list()
        for el in outp:
            try:
                num = [c for c in el if c.isdigit()]
                num = int(el)
                result.append(num)
            except:
                pass

        if len(result) == 2:
            return result
        elif len(result) == 1:
            return result.append(0)
        else:
            return [0, 0]

    def fill_in(self):
        self.tableWidget.clearContents()
        rowPosition = self.tableWidget.rowCount()        
        

        names = []
        ids = []
        x = 0
        z = 0
        k = 0
        for proc in process_iter():
            name = proc.name()
            y = len(name)
            if y>x:
                x = y
            if y<x:
                k = y
            id = proc.pid
            names.insert(z, name)
            ids.insert(z, id)
            z += 1

        for b in range(len(names)-1):
            z = x
            rowPosition = self.tableWidget.rowCount()    
            self.tableWidget.insertRow(rowPosition)
            tmp = self.get_page_faults(ids[b])
            if tmp and len(tmp) == 2:
                minpf, majpf = tmp
            else:
                minpf, majpf = 0, 0

            self.tableWidget.setItem(rowPosition , 0, QtWidgets.QTableWidgetItem(f'{ids[b]}'))
            self.tableWidget.setItem(rowPosition , 1, QtWidgets.QTableWidgetItem(f'{minpf}'))
            self.tableWidget.setItem(rowPosition , 2, QtWidgets.QTableWidgetItem(f'{majpf}'))
            self.tableWidget.setItem(rowPosition , 3, QtWidgets.QTableWidgetItem(names[b]))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = ProcWindow(Form)
    Form.show()
    sys.exit(app.exec_())
